GRANT SELECT ON public.products TO anon;
GRANT SELECT ON public.product_images TO anon;
GRANT SELECT ON public.product_variants TO anon;
GRANT SELECT ON public.categories TO anon;
GRANT SELECT ON public.reviews TO anon;
GRANT SELECT ON public.delivery_zones TO anon;
GRANT SELECT ON public.site_settings TO anon;
GRANT SELECT ON public.homepage_content TO anon;

INSERT INTO public.homepage_content (section, content, active, display_order) VALUES
('shop_hero', '{"eyebrow":{"en":"The Collection","fr":"La Collection","ar":"المجموعة"},"title":{"en":"Handmade leather, made to be carried for years","fr":"Cuir fait main, conçu pour durer des années","ar":"جلد مصنوع يدويًا ليرافقك لسنوات"},"subtitle":{"en":"Every piece is cut, stitched and burnished by hand in our Taroudant workshop. Cash on Delivery across Morocco.","fr":"Chaque pièce est coupée, cousue et lustrée à la main dans notre atelier de Taroudant. Paiement à la livraison partout au Maroc.","ar":"كل قطعة تُقص وتُخاط وتُصقل يدويًا في ورشتنا بتارودانت. الدفع عند الاستلام في كل المغرب."},"primaryLabel":{"en":"Browse Collection","fr":"Voir la collection","ar":"تصفح المجموعة"},"secondaryLabel":{"en":"Order on WhatsApp","fr":"Commander sur WhatsApp","ar":"اطلب عبر واتساب"},"image":""}', true, 20),
('shop_featured', '{"eyebrow":{"en":"Selected","fr":"Sélection","ar":"مختارة"},"title":{"en":"Featured pieces","fr":"Pièces en vedette","ar":"قطع مميزة"},"subtitle":{"en":"Hand-picked from the workshop bench.","fr":"Choisies à la main sur l''établi.","ar":"مختارة بعناية من طاولة الورشة."}}', true, 21),
('shop_categories', '{"eyebrow":{"en":"Browse","fr":"Parcourir","ar":"تصفح"},"title":{"en":"Shop by category","fr":"Acheter par catégorie","ar":"تسوق حسب الفئة"},"hidden":[]}', true, 22),
('shop_collection', '{"eyebrow":{"en":"All pieces","fr":"Toutes les pièces","ar":"كل القطع"},"title":{"en":"The full collection","fr":"La collection complète","ar":"المجموعة الكاملة"},"subtitle":{"en":"Every active piece, straight from the workshop.","fr":"Chaque pièce disponible, directement de l''atelier.","ar":"كل قطعة متوفرة، مباشرة من الورشة."}}', true, 23),
('shop_craft', '{"eyebrow":{"en":"Our craft","fr":"Notre savoir-faire","ar":"حرفتنا"},"title":{"en":"Cut, stitched and burnished by hand","fr":"Coupé, cousu et lustré à la main","ar":"يُقص ويُخاط ويُصقل يدويًا"},"body":{"en":"We start with full-grain Moroccan goat leather, tanned the traditional way. Each panel is cut by hand, saddle-stitched with waxed thread, then the edges are sanded and burnished until they are smooth as glass. A single wallet takes several hours of bench work.","fr":"Nous partons d''un cuir de chèvre marocain pleine fleur, tanné de manière traditionnelle. Chaque panneau est coupé à la main, cousu au point sellier avec du fil ciré, puis les tranches sont poncées et lustrées jusqu''à devenir lisses comme du verre. Un seul portefeuille demande plusieurs heures d''établi.","ar":"نبدأ من جلد الماعز المغربي الكامل، مدبوغ بالطريقة التقليدية. تُقص كل قطعة يدويًا وتُخاط بخيط مشمّع، ثم تُصقل الحواف حتى تصبح ناعمة كالزجاج. المحفظة الواحدة تتطلب ساعات من العمل."},"points":{"en":["Full-grain Moroccan goat leather","Hand saddle-stitching with waxed thread","Hand-burnished edges","Made in Taroudant, Morocco"],"fr":["Cuir de chèvre marocain pleine fleur","Point sellier à la main, fil ciré","Tranches lustrées à la main","Fabriqué à Taroudant, Maroc"],"ar":["جلد ماعز مغربي كامل","خياطة يدوية بخيط مشمّع","حواف مصقولة يدويًا","صناعة تارودانت، المغرب"]}}', true, 24),
('shop_packaging', '{"eyebrow":{"en":"Packaging","fr":"Emballage","ar":"التغليف"},"title":{"en":"Arrives gift-ready","fr":"Livré prêt à offrir","ar":"يصلك جاهزًا كهدية"},"body":{"en":"Every order leaves the workshop wrapped in natural burlap and twine, placed inside a rigid Loner Leather box with a handwritten thank-you card. Nothing else to add before you give it away.","fr":"Chaque commande quitte l''atelier enveloppée de toile de jute et de ficelle, dans une boîte rigide Loner Leather avec une carte de remerciement manuscrite. Rien à ajouter avant de l''offrir.","ar":"كل طلب يغادر الورشة ملفوفًا بالخيش والحبل داخل علبة Loner Leather مع بطاقة شكر مكتوبة بخط اليد."}}', true, 25),
('shop_delivery', '{"eyebrow":{"en":"Delivery","fr":"Livraison","ar":"التوصيل"},"title":{"en":"Simple, safe delivery","fr":"Livraison simple et sûre","ar":"توصيل بسيط وآمن"},"items":{"en":[{"title":"Cash on Delivery","text":"Pay the courier in cash when your parcel arrives."},{"title":"Delivery across Morocco","text":"All 12 regions, cities and rural communes."},{"title":"WhatsApp support","text":"Talk to a real person before and after your order."},{"title":"Fast shipping","text":"Dispatched from Taroudant within 24–48 hours."}],"fr":[{"title":"Paiement à la livraison","text":"Payez le livreur en espèces à la réception."},{"title":"Livraison partout au Maroc","text":"Les 12 régions, villes et communes rurales."},{"title":"Support WhatsApp","text":"Parlez à une vraie personne avant et après votre commande."},{"title":"Expédition rapide","text":"Expédié de Taroudant sous 24 à 48 heures."}],"ar":[{"title":"الدفع عند الاستلام","text":"ادفع نقدًا لعامل التوصيل عند وصول الطرد."},{"title":"توصيل لكل المغرب","text":"كل الجهات والمدن والجماعات القروية."},{"title":"دعم واتساب","text":"تحدث مع شخص حقيقي قبل وبعد الطلب."},{"title":"شحن سريع","text":"يُشحن من تارودانت خلال 24 إلى 48 ساعة."}]}}', true, 26),
('shop_reviews', '{"eyebrow":{"en":"Reviews","fr":"Avis","ar":"آراء"},"title":{"en":"What customers say","fr":"Ce que disent nos clients","ar":"ماذا يقول عملاؤنا"}}', true, 27),
('shop_faq', '{"eyebrow":{"en":"FAQ","fr":"FAQ","ar":"أسئلة"},"title":{"en":"Questions before you order","fr":"Questions avant de commander","ar":"أسئلة قبل الطلب"},"items":[{"q":{"en":"How long does delivery take?","fr":"Quel est le délai de livraison ?","ar":"كم يستغرق التوصيل؟"},"a":{"en":"Orders leave Taroudant within 24–48 hours. Delivery takes 24–48 hours in major cities and 2–4 working days elsewhere in Morocco.","fr":"Les commandes quittent Taroudant sous 24 à 48 heures. La livraison prend 24 à 48 heures dans les grandes villes et 2 à 4 jours ouvrables ailleurs au Maroc.","ar":"تغادر الطلبات تارودانت خلال 24-48 ساعة. التوصيل يستغرق 24-48 ساعة في المدن الكبرى و2-4 أيام عمل في باقي المغرب."}},{"q":{"en":"Can I pay cash on delivery?","fr":"Puis-je payer à la livraison ?","ar":"هل يمكنني الدفع عند الاستلام؟"},"a":{"en":"Yes. Cash on Delivery is our main payment method — nothing upfront, no card details.","fr":"Oui. Le paiement à la livraison est notre méthode principale — rien à avancer, aucune carte.","ar":"نعم. الدفع عند الاستلام هو وسيلتنا الأساسية — بدون أي دفع مسبق."}},{"q":{"en":"Is the leather genuine?","fr":"Le cuir est-il véritable ?","ar":"هل الجلد طبيعي؟"},"a":{"en":"Every piece is genuine full-grain Moroccan goat leather, tanned in Morocco. No bonded leather, no PU coating.","fr":"Chaque pièce est en cuir de chèvre marocain pleine fleur véritable, tanné au Maroc. Ni cuir reconstitué, ni revêtement PU.","ar":"كل قطعة من جلد ماعز مغربي طبيعي كامل، مدبوغ في المغرب. بدون جلد مضغوط أو طلاء صناعي."}},{"q":{"en":"Can I order on WhatsApp?","fr":"Puis-je commander sur WhatsApp ?","ar":"هل يمكنني الطلب عبر واتساب؟"},"a":{"en":"Absolutely. Tap any WhatsApp button and we will confirm your order, address and delivery time in a short chat.","fr":"Bien sûr. Touchez un bouton WhatsApp et nous confirmerons votre commande, votre adresse et le délai en quelques messages.","ar":"بالتأكيد. اضغط أي زر واتساب وسنؤكد طلبك وعنوانك وموعد التوصيل في محادثة قصيرة."}}]}', true, 28),
('shop_cta', '{"title":{"en":"Order your handmade leather goods today","fr":"Commandez vos articles en cuir fait main aujourd''hui","ar":"اطلب منتجاتك الجلدية المصنوعة يدويًا اليوم"},"subtitle":{"en":"Cash on Delivery across Morocco. Wrapped, boxed and ready to gift.","fr":"Paiement à la livraison partout au Maroc. Emballé, mis en boîte et prêt à offrir.","ar":"الدفع عند الاستلام في كل المغرب. مغلّف وجاهز كهدية."},"primaryLabel":{"en":"Shop Collection","fr":"Voir la collection","ar":"تسوق المجموعة"},"secondaryLabel":{"en":"Order on WhatsApp","fr":"Commander sur WhatsApp","ar":"اطلب عبر واتساب"}}', true, 29);